# BifacialvF- PVMISMATCH Testing Landscape and Portrait Results.

In [1]:
import bifacialvf
import pandas as pd

In [2]:
frontGTIrow=[53.01720526, 55.32772694, 55.78247445, 55.69094834, 55.62417481, 55.59217422]
backGTIrow=[8.550246348, 4.626045218, 4.406054333, 6.141527447, 9.211464402, 12.87567548]

portraitorlandscape='portrait'
sensorsy=6
debug=True
                       
cellCenterPVM, stdpl, cellsx, cellsy = bifacialvf.analysis.setupforPVMismatch(portraitorlandscape=portraitorlandscape, sensorsy=sensorsy)

PowerAveraged, PowerDetailed, sunmatDetailed, sunmatAveraged = bifacialvf.analysis.calculateVFPVMismatch(cellCenterPVM=cellCenterPVM, stdpl=stdpl, cellsx=cellsx, cellsy=cellsy, sensorsy=sensorsy, frontGTIrow=frontGTIrow, backGTIrow=backGTIrow, debug=debug)

print("Results: ", round(PowerAveraged,2), round(PowerDetailed,2))

print(portraitorlandscape, cellsx, cellsy)
print(pd.DataFrame(stdpl))
print(pd.DataFrame(sunmatAveraged).round(3))
pd.DataFrame(sunmatDetailed).round(3)

Results:  15.51 15.22
portrait 8 12
     0   1   2   3   4   5   6   7
0    0  23  24  47  48  71  72  95
1    1  22  25  46  49  70  73  94
2    2  21  26  45  50  69  74  93
3    3  20  27  44  51  68  75  92
4    4  19  28  43  52  67  76  91
5    5  18  29  42  53  66  77  90
6    6  17  30  41  54  65  78  89
7    7  16  31  40  55  64  79  88
8    8  15  32  39  56  63  80  87
9    9  14  33  38  57  62  81  86
10  10  13  34  37  58  61  82  85
11  11  12  35  36  59  60  83  84
        0      1      2      3      4      5      6      7
0   0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
1   0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
2   0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
3   0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
4   0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
5   0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
6   0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
7   0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
8   0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
9   0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
10  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
11  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063

        0      1      2      3      4      5      6      7
0   0.061  0.061  0.061  0.061  0.061  0.061  0.061  0.061
1   0.060  0.060  0.060  0.060  0.060  0.060  0.060  0.060
2   0.060  0.060  0.060  0.060  0.060  0.060  0.060  0.060
3   0.060  0.060  0.060  0.060  0.060  0.060  0.060  0.060
4   0.061  0.061  0.061  0.061  0.061  0.061  0.061  0.061
5   0.061  0.061  0.061  0.061  0.061  0.061  0.061  0.061
6   0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
7   0.064  0.064  0.064  0.064  0.064  0.064  0.064  0.064
8   0.066  0.066  0.066  0.066  0.066  0.066  0.066  0.066
9   0.068  0.068  0.068  0.068  0.068  0.068  0.068  0.068
10  0.068  0.068  0.068  0.068  0.068  0.068  0.068  0.068
11  0.068  0.068  0.068  0.068  0.068  0.068  0.068  0.068

In [3]:
frontGTIrow=[53.01720526, 55.32772694, 55.78247445, 55.69094834, 55.62417481, 55.59217422]
backGTIrow=[8.550246348, 4.626045218, 4.406054333, 6.141527447, 9.211464402, 12.87567548]

portraitorlandscape='landscape'
sensorsy=6
                       
cellCenterPVM, stdpl, cellsx, cellsy = bifacialvf.analysis.setupforPVMismatch(portraitorlandscape=portraitorlandscape, sensorsy=sensorsy)

PowerAveraged, PowerDetailed, sunmatDetailed, sunmatAveraged = bifacialvf.analysis.calculateVFPVMismatch(cellCenterPVM, stdpl, cellsx, cellsy, sensorsy, frontGTIrow, backGTIrow, debug=True)

print("Results: ", round(PowerAveraged,2), round(PowerDetailed,2))

print(portraitorlandscape, cellsx, cellsy)
print(pd.DataFrame(stdpl))
print(pd.DataFrame(sunmatAveraged).round(3))
pd.DataFrame(sunmatDetailed).round(3)

Results:  15.51 15.14
landscape 12 8
   0   1   2   3   4   5   6   7   8   9   10  11
0   0   1   2   3   4   5   6   7   8   9  10  11
1  23  22  21  20  19  18  17  16  15  14  13  12
2  24  25  26  27  28  29  30  31  32  33  34  35
3  47  46  45  44  43  42  41  40  39  38  37  36
4  48  49  50  51  52  53  54  55  56  57  58  59
5  71  70  69  68  67  66  65  64  63  62  61  60
6  72  73  74  75  76  77  78  79  80  81  82  83
7  95  94  93  92  91  90  89  88  87  86  85  84
      0      1      2      3      4      5      6      7      8      9   \
0  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
1  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
2  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
3  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
4  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
5  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
6  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
7  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063

      10     11
0  0.063  0.063
1  0.063  0.063
2  0.063  0.063
3  0.063  0.063
4  0.063  0.063
5  0.063  0.063
6  0.063  0.063
7  0.063  0.063

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.061,0.061,0.061,0.061,0.061,0.061,0.061,0.061,0.061,0.061,0.061,0.061
1,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060
2,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060
3,0.061,0.061,0.061,0.061,0.061,0.061,0.061,0.061,0.061,0.061,0.061,0.061
4,0.063,0.063,0.063,0.063,0.063,0.063,0.063,0.063,0.063,0.063,0.063,0.063
5,0.065,0.065,0.065,0.065,0.065,0.065,0.065,0.065,0.065,0.065,0.065,0.065
6,0.068,0.068,0.068,0.068,0.068,0.068,0.068,0.068,0.068,0.068,0.068,0.068
7,0.068,0.068,0.068,0.068,0.068,0.068,0.068,0.068,0.068,0.068,0.068,0.068